# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Release packages

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    name: Publish packages to NPM

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    env:
      RAW_COMMIT_MESSAGE: 'chore: release package(s)'

    outputs:
      published: ${{ steps.changesets.outputs.published }}

    steps:
      - name: â¬ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ•º Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-and-pnpm

      - name: ğŸ“¦ Install dependencies
        run: pnpm install --frozen-lockfile

      - name: ğŸ”¨ Build
        run: pnpm --filter \!@elysiajs/documentation build

      - name: âœï¸ Generate commit message
        id: devmoji
        run: |
          MESSAGE=$(npx --no -- devmoji --format shortcode --text ${{ toJSON(env.RAW_COMMIT_MESSAGE) }})
          echo "MESSAGE=$MESSAGE" >> $GITHUB_OUTPUT

      - name: ğŸš€ Create pull request or publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm publish -r
          commit: ${{ steps.devmoji.outputs.MESSAGE }}
          title: ${{ steps.devmoji.outputs.MESSAGE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  release:
    name: Release GitHub packages

    runs-on: ubuntu-latest

    needs: publish
    if: ${{ needs.publish.outputs.published }}

    steps:
      - name: ğŸ‘€ Get package.json version
        id: package-json-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: ğŸ Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-json-version.outputs.current-version }}
          release_name: ${{ github.event.pull_request.title }}
