# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Release packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish packages to NPM

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    env:
      RAW_COMMIT_MESSAGE: 'chore: release package(s)'

    steps:
      - name: â¬ Checkout repository
        uses: actions/checkout@v4

      - name: ðŸ•º Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-and-pnpm

      - name: ðŸ“¦ Install dependencies
        run: pnpm install --frozen-lockfile

      - name: ðŸ”¨ Build
        run: pnpm build --filter !@elysiajs/documentation

      - name: âœï¸ Generate commit message
        id: devmoji
        run: |
          MESSAGE=$(npx --no -- devmoji --format shortcode --text ${{ toJSON(env.RAW_COMMIT_MESSAGE) }})
          echo "MESSAGE=$MESSAGE" >> $GITHUB_OUTPUT

      - name: ðŸš€ Create pull request or publish to npm
        uses: changesets/action@v1
        id: changesets
        with:
          publish: pnpm changeset publish
          commit: ${{ steps.devmoji.outputs.MESSAGE }}
          title: ${{ steps.devmoji.outputs.MESSAGE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
