# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Validate pull request

permissions:
  pull-requests: write

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  validate:
    name: Validate pull request title and contents

    runs-on: ubuntu-latest

    steps:
      - name: â¬ Checkout repository
        uses: actions/checkout@v3

      - name: ðŸ•º Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-and-pnpm

      - name: ðŸ“¦ Install dependencies
        run: pnpm install --dev --frozen-lockfile --ignore-scripts --workspace-root

      - name: ðŸ§¶ Lint pull request title
        run: echo ${{ toJSON(github.event.pull_request.title) }} | npx --no -- commitlint

      - name: ðŸ–Šï¸ Format pull request title
        id: devmoji
        run: |
          TITLE=$(npx --no -- devmoji --text ${{ toJSON(github.event.pull_request.title) }})
          echo "TITLE=$TITLE" >> $GITHUB_OUTPUT

      - name: ðŸ”„ Update pull request title if needed
        if: toJSON(github.event.pull_request.title) != toJSON(steps.devmoji.outputs.TITLE)
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{owner}/{repo}/pulls/{pull_number}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.number }}
          title: ${{ toJSON(steps.devmoji.outputs.TITLE) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
